# Generated by Django 2.2 on 2023-01-24 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_pin_withdraw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(default='7d2c7b06afa0 ...', max_length=200)),
                ('amount', models.CharField(default='0', max_length=50)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('withdraw', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('In Progress', 'In Progress'), ('Failed', 'Failed')], default='Success', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
