# Generated by Django 2.2 on 2023-01-24 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_tran'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tran',
            old_name='withdraw',
            new_name='loss',
        ),
    ]
