# Generated by Django 2.2 on 2023-01-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20230124_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pair',
            field=models.CharField(blank=True, default='BTC/USDT', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='accountbalance',
            field=models.CharField(default='500,000', max_length=50),
        ),
    ]
