# Generated by Django 2.2 on 2023-02-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20230201_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pro',
            field=models.BooleanField(default=False),
        ),
    ]
