# Generated by Django 2.2 on 2023-04-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_sta_stake'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', max_length=50)),
                ('profit', models.CharField(default='0', max_length=50)),
                ('mindeposit', models.CharField(default='0', max_length=50)),
                ('maxdeposit', models.CharField(default='0', max_length=50)),
                ('duration', models.CharField(default='0', max_length=50)),
            ],
        ),
    ]
