# Generated by Django 2.2 on 2023-04-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='pair',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rank',
            field=models.CharField(blank=True, default='Beginner', max_length=50),
        ),
    ]
