# Generated by Django 2.2 on 2023-04-21 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20230420_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upgrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', max_length=50)),
                ('profit', models.CharField(default='0', max_length=50)),
                ('mindeposit', models.CharField(default='0', max_length=50)),
            ],
        ),
    ]
