# Generated by Django 2.2 on 2023-05-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_upgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='pro_ny6h2o.png', upload_to=''),
        ),
    ]
